volumes:
  static:
  media:
  postgres_data:

services:
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./static:/static_collected/
      - ./media:/media/

  nginx:
    image: nginx:1.21.6
    ports:
      - 80:80
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
      - ./static_collected:/var/html/static/
      - ./media:/var/html/media
    depends_on:
      - web
