# Generated by Django 4.1 on 2022-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": ("pub_date",),
                "ordering": ("-pub_date",),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="is_posted",
            field=models.BooleanField(default=False),
        ),
    ]
